# Generated by Django 5.2.17 on 2026-08-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('clasificacion', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_estreno', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='cartelera.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='cartelera.sala')),
            ],
            options={
                'ordering': ['fecha', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.PositiveIntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='butacas', to='cartelera.sala')),
            ],
            options={
                'ordering': ['sala', 'fila', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('butaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='cartelera.butaca')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='cartelera.funcion')),
            ],
            options={
                'ordering': ['-fecha_compra'],
                'constraints': [models.UniqueConstraint(fields=('funcion', 'butaca'), name='una_entrada_por_butaca_y_funcion')],
            },
        ),
        migrations.AddConstraint(
            model_name='butaca',
            constraint=models.UniqueConstraint(fields=('sala', 'fila', 'numero'), name='butaca_unica_por_sala'),
        ),
    ]
